Enhancement - switch to polkit

diff --git a/thus b/thus
--- a/thus
+++ b/thus
@@ -1,3 +1,13 @@
 #!/bin/bash
 
-/usr/bin/env python /usr/share/thus/thus.py ${@}
+if [ $(which pkexec) ]; then
+	pkexec --disable-internal-agent /usr/bin/env python /usr/share/thus/thus.py ${@}
+elif [ $(which sudo) ]; then
+	sudo -E /usr/bin/env python /usr/share/thus/thus.py ${@}
+else
+    # do UID checking here so someone can at least get usage instructions
+    if [ "$EUID" != "0" ]; then
+        echo "error: thus must be run as root."
+        exit 1
+    fi
+fi
